name: 'Run Standard with Reviewdog'
description: '🐶 Run Standard Ruby with Reviewdog on pull requests to improve code review experience.'
author: 'kirillplatonov'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  standard_version:
    description: 'Standard version'
  standard_plugins:
    description: 'Standard plugins'
    default: 'standard-rails'
  standard_flags:
    description: 'Standard flags. (standardrb <standard_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'rubocop'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  workdir:
    description: "The directory from which to look for and run Standard. Default '.'"
    default: '.'
  skip_install:
    description: "Do not install Standard or its plugins. Default: `false`"
    default: 'false'
  use_bundler:
    description: "Run Standard with bundle exec. Default: `false`"
    default: 'false'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.14.1
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_STANDARD_VERSION: ${{ inputs.standard_version }}
        INPUT_STANDARD_PLUGINS: ${{ inputs.standard_plugins }}
        INPUT_STANDARD_FLAGS: ${{ inputs.standard_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_SKIP_INSTALL: ${{ inputs.skip_install }}
        INPUT_USE_BUNDLER: ${{ inputs.use_bundler }}
branding:
  icon: 'check-circle'
  color: 'red'
